// src/utils/generateOpeningRecord.js
import jsPDF from 'jspdf';
import 'jspdf-autotable'; // Plugin for tables

/**
 * Generates the Opening Record PDF.
 * @param {object} project - The bidding project details.
 * @param {array} suppliers - List of suppliers and their bid status.
 * @param {object} currentUser - The Auditor performing the action.
 */
export const generateOpeningRecord = (project, suppliers, currentUser) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // 1. Header
    doc.setFontSize(22);
    doc.text("Procurement Opening Record", pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(12);
    doc.text(`Generated By: ${currentUser.name} (${currentUser.role})`, 14, 30);
    doc.text(`Date: ${new Date().toLocaleString()}`, 14, 38);

    // 2. Project Info
    doc.setFontSize(14);
    doc.text("Project Details", 14, 50);
    doc.setLineWidth(0.5);
    doc.line(14, 52, 60, 52); // Underline

    doc.setFontSize(10);
    doc.text(`Project Name: ${project.title}`, 14, 60);
    doc.text(`Project ID: ${project.id}`, 14, 66);
    doc.text(`Closing Time: ${new Date(project.endTime).toLocaleString()}`, 14, 72);

    // 3. Supplier Table
    const tableColumn = ["ID", "Supplier Name", "Status", "Bid Submission Time", "Quoted Price (Fill Manually)"];
    const tableRows = [];

    suppliers.forEach(supplier => {
        const bidData = [
            supplier.id,
            supplier.name,
            supplier.hasBid ? "Submitted" : "No Bid",
            supplier.hasBid ? new Date(supplier.bidTime).toLocaleString() : "-",
            "" // Empty column for manual entry
        ];
        tableRows.push(bidData);
    });

    doc.autoTable({
        startY: 80,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185] }, // Blue header
    });

    // 4. Signatures
    const finalY = doc.lastAutoTable.finalY || 150;

    doc.text("Auditor Signature:", 14, finalY + 30);
    doc.line(50, finalY + 30, 100, finalY + 30);

    doc.text("Witness Signature:", 120, finalY + 30);
    doc.line(155, finalY + 30, 200, finalY + 30);

    // 5. Save
    doc.save(`Opening_Record_${project.id}.pdf`);
};
