// src/utils/generateOpeningRecord.js
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // Updated import

/**
 * Generates the Opening Record PDF.
 * @param {object} project - The bidding project details.
 * @param {array} suppliers - List of suppliers and their bid status.
 * @param {object} currentUser - The Auditor performing the action.
 */
export const generateOpeningRecord = (project, suppliers, currentUser) => {
    // Create PDF with proper Unicode support
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
        putOnlyUsedFonts: true,
        floatPrecision: 16
    });

    const pageWidth = doc.internal.pageSize.getWidth();

    // Use default font which has better Unicode support in jsPDF 3.x
    // The default font in jsPDF 3.x uses a Unicode-compatible encoding
    doc.setFont('helvetica', 'normal');

    // 1. Header
    doc.setFontSize(22);
    doc.text("Procurement Opening Record", pageWidth / 2, 20, { align: 'center' });

    const formatDate = (dateStr) => {
        if (!dateStr) return "-";
        const d = new Date(dateStr);
        return d.getFullYear() + "/" +
            String(d.getMonth() + 1).padStart(2, '0') + "/" +
            String(d.getDate()).padStart(2, '0') + " " +
            String(d.getHours()).padStart(2, '0') + ":" +
            String(d.getMinutes()).padStart(2, '0') + ":" +
            String(d.getSeconds()).padStart(2, '0');
    };

    doc.setFontSize(12);
    doc.text(`Generated By: ${currentUser.name} (${currentUser.role})`, 14, 30);
    doc.text(`Date: ${formatDate(new Date())}`, 14, 38);

    // 2. Project Info
    doc.setFontSize(14);
    doc.text("Project Details", 14, 50);
    doc.setLineWidth(0.5);
    doc.line(14, 52, 60, 52); // Underline

    doc.setFontSize(10);
    doc.text(`Project Name: ${project.title}`, 14, 60);
    doc.text(`Project ID: ${project.id}`, 14, 66);
    doc.text(`Created By: ${project.createdBy || 'N/A'}`, 14, 72);
    doc.text(`Closing Time: ${formatDate(project.endTime)}`, 14, 78);
    doc.text(`Currency: ${project.currency || 'VND'}`, 14, 84);

    // 3. Supplier Table
    const tableColumn = ["ID", "Supplier Name", "Status", "Submission Time", "Bid Price", "Negotiated Price"];
    const tableRows = [];

    suppliers.forEach(supplier => {
        const bidPrice = supplier.price ? supplier.price.toLocaleString() : "-";

        const bidData = [
            supplier.id,
            supplier.name,
            supplier.hasBid ? "Submitted" : "No Bid",
            formatDate(supplier.bidTime),
            bidPrice,
            "" // Empty column for Negotiated Price
        ];
        tableRows.push(bidData);
    });

    autoTable(doc, {
        startY: 91,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: {
            fillColor: [41, 128, 185],
            font: 'helvetica',
            fontStyle: 'bold'
        },
        bodyStyles: {
            font: 'helvetica',
            fontStyle: 'normal'
        },
        styles: {
            font: 'helvetica',
            fontSize: 10,
            cellPadding: 3,
            overflow: 'linebreak',
            cellWidth: 'wrap'
        },
        columnStyles: {
            0: { cellWidth: 40 }, // ID
            1: { cellWidth: 50 }, // Supplier Name
            2: { cellWidth: 25 }, // Status
            3: { cellWidth: 35 }, // Submission Time
            4: { cellWidth: 25 }, // Bid Price
            5: { cellWidth: 25 }  // Negotiated Price
        }
    });

    // 4. Signatures
    const finalY = doc.lastAutoTable.finalY || 150;

    doc.text("Auditor Signature:", 14, finalY + 30);
    doc.line(50, finalY + 30, 100, finalY + 30);

    doc.text("Witness Signature:", 120, finalY + 30);
    doc.line(155, finalY + 30, 200, finalY + 30);

    // 5. Save with sanitized filename (Manual Blob method to ensure browser respects filename)
    const safeTitle = (project.title || "Project").replace(/[^a-z0-9\u4e00-\u9fa5]/gi, '_');
    const filename = `Opening_Record_${project.id}_${safeTitle}.pdf`;

    console.log("Saving PDF manually as:", filename);

    // Generate blob directly
    const pdfBlob = doc.output('blob');

    // Create object URL
    const url = URL.createObjectURL(pdfBlob);

    // Create temporary link element
    const link = document.createElement('a');
    link.href = url;
    link.download = filename; // This forces the filename

    // Append to body (required for FF), click, and remove
    document.body.appendChild(link);
    link.click();

    // Cleanup
    setTimeout(() => {
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }, 100);
};
