// src/utils/generateOpeningRecord.js
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // Updated import

/**
 * Generates the Opening Record PDF.
 * @param {object} project - The bidding project details.
 * @param {array} suppliers - List of suppliers and their bid status.
 * @param {object} currentUser - The Auditor performing the action.
 */
export const generateOpeningRecord = (project, suppliers, currentUser) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // 1. Header
    doc.setFontSize(22);
    doc.text("Procurement Opening Record", pageWidth / 2, 20, { align: 'center' });

    const formatDate = (dateStr) => {
        if (!dateStr) return "-";
        const d = new Date(dateStr);
        return d.getFullYear() + "/" +
            String(d.getMonth() + 1).padStart(2, '0') + "/" +
            String(d.getDate()).padStart(2, '0') + " " +
            String(d.getHours()).padStart(2, '0') + ":" +
            String(d.getMinutes()).padStart(2, '0') + ":" +
            String(d.getSeconds()).padStart(2, '0');
    };

    doc.setFontSize(12);
    doc.text(`Generated By: ${currentUser.name} (${currentUser.role})`, 14, 30);
    doc.text(`Date: ${formatDate(new Date())}`, 14, 38);

    // 2. Project Info
    doc.setFontSize(14);
    doc.text("Project Details", 14, 50);
    doc.setLineWidth(0.5);
    doc.line(14, 52, 60, 52); // Underline

    doc.setFontSize(10);
    doc.text(`Project Name: ${project.title}`, 14, 60);
    doc.text(`Project ID: ${project.id}`, 14, 66);
    doc.text(`Closing Time: ${formatDate(project.endTime)}`, 14, 72);
    doc.text(`Currency: ${project.currency || 'TWD'}`, 14, 78);

    // 3. Supplier Table
    const tableColumn = ["ID", "Supplier Name", "Status", "Submission Time", "Bid Price", "Negotiated Price"];
    const tableRows = [];

    suppliers.forEach(supplier => {
        const bidPrice = supplier.price ? `${project.currency || 'TWD'} ${supplier.price.toLocaleString()}` : "-";
        const bidData = [
            supplier.id,
            supplier.name,
            supplier.hasBid ? "Submitted" : "No Bid",
            formatDate(supplier.bidTime),
            bidPrice,
            "" // Empty column for Negotiated Price
        ];
        tableRows.push(bidData);
    });

    autoTable(doc, {
        startY: 85, // Adjusted for extra line
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185] }, // Blue header
    });

    // 4. Signatures
    const finalY = doc.lastAutoTable.finalY || 150;

    doc.text("Auditor Signature:", 14, finalY + 30);
    doc.line(50, finalY + 30, 100, finalY + 30);

    doc.text("Witness Signature:", 120, finalY + 30);
    doc.line(155, finalY + 30, 200, finalY + 30);

    // 5. Return blob url instead of save, or just save
    // User wants persistent link. We can't really store the file in mock.
    // The "Persistent Link" effectively just means re-generating the PDF with the same data.
    // So distinct save is fine for user experience as "Download".
    doc.save(`Opening_Record_${project.id}.pdf`);
};
